-- MySQL Script generated by MySQL Workbench
-- Thu Nov 15 12:35:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio` (
  `id_estudio` INT NOT NULL,
  `Nombre_estudio` VARCHAR(45) NOT NULL,
  `Descripcion_estudio` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_estudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuestionario` (
  `id_cuestionario` INT NOT NULL,
  `estudio_id_estudio` INT NOT NULL,
  `Nombre_cuestionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cuestionario`, `estudio_id_estudio`),
  INDEX `fk_cuestionario_estudio1_idx` (`estudio_id_estudio` ASC),
  CONSTRAINT `fk_cuestionario_estudio1`
    FOREIGN KEY (`estudio_id_estudio`)
    REFERENCES `mydb`.`estudio` (`id_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reactivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reactivo` (
  `id_reactivo` INT NOT NULL,
  `reactivo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_reactivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`asignacion_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asignacion_pregunta` (
  `id_cuestionario` INT NOT NULL,
  `id_estudio` INT NOT NULL,
  `id_reactivo` INT NOT NULL,
  INDEX `fk_asignacion_pregunta_cuestionario1_idx` (`id_cuestionario` ASC, `id_estudio` ASC),
  INDEX `fk_asignacion_pregunta_reactivo1_idx` (`id_reactivo` ASC),
  PRIMARY KEY (`id_cuestionario`, `id_estudio`, `id_reactivo`),
  CONSTRAINT `fk_asignacion_pregunta_cuestionario1`
    FOREIGN KEY (`id_cuestionario` , `id_estudio`)
    REFERENCES `mydb`.`cuestionario` (`id_cuestionario` , `estudio_id_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_pregunta_reactivo1`
    FOREIGN KEY (`id_reactivo`)
    REFERENCES `mydb`.`reactivo` (`id_reactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  `Nombre_tipo` VARCHAR(45) NOT NULL,
  `Descripcion_usuario` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL DEFAULT 0,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_tipo_usuario`),
  INDEX `fk_usuario_tipo_usuario_idx` (`id_tipo_usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estudio_asignado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio_asignado` (
  `id_usuario` INT NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  `id_estudio` INT NOT NULL,
  INDEX `fk_estudio_asignado_usuario1_idx` (`id_usuario` ASC, `id_tipo_usuario` ASC),
  INDEX `fk_estudio_asignado_estudio1_idx` (`id_estudio` ASC),
  PRIMARY KEY (`id_usuario`, `id_tipo_usuario`, `id_estudio`),
  CONSTRAINT `fk_estudio_asignado_usuario1`
    FOREIGN KEY (`id_usuario` , `id_tipo_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudio_asignado_estudio1`
    FOREIGN KEY (`id_estudio`)
    REFERENCES `mydb`.`estudio` (`id_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta` (
  `id_respuesta` INT NOT NULL,
  `id_reactivo` INT NOT NULL,
  `respuesta` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_respuesta`, `id_reactivo`),
  INDEX `fk_respuesta_reactivo1_idx` (`id_reactivo` ASC),
  CONSTRAINT `fk_respuesta_reactivo1`
    FOREIGN KEY (`id_reactivo`)
    REFERENCES `mydb`.`reactivo` (`id_reactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ci_sessions` (
  `usuario_id_usuario` INT NOT NULL,
  `usuario_id_tipo_usuario` INT NOT NULL,
  `ip_adress` VARCHAR(45) NULL,
  `timestamp` INT(10) NULL,
  INDEX `fk_ci_sessions_usuario1_idx` (`usuario_id_usuario` ASC, `usuario_id_tipo_usuario` ASC),
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_ci_sessions_usuario1`
    FOREIGN KEY (`usuario_id_usuario` , `usuario_id_tipo_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ci_sessions` (
  `usuario_id_usuario` INT NOT NULL,
  `usuario_id_tipo_usuario` INT NOT NULL,
  `ip_adress` VARCHAR(45) NULL,
  `timestamp` INT(10) NULL,
  INDEX `fk_ci_sessions_usuario1_idx` (`usuario_id_usuario` ASC, `usuario_id_tipo_usuario` ASC),
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_ci_sessions_usuario1`
    FOREIGN KEY (`usuario_id_usuario` , `usuario_id_tipo_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
